### ISSUE TITLE
Filesystem cache not working

### ISSUE THREAD

**Issue by art2limit** [GoogleChrome/rendertron#410]
this is my config.json:
{
    "cache": "filesystem",
    "cacheConfig": {
    "cacheDurationMinutes": -1,
    "cacheMaxEntries": -1,
    "snapshotDir": "/home/name/rendertron-cache/"
    },
    "timeout": 60000
}

but `rendertron-cache` is not created or after i create it it's empty

**Comment by dwsmart** [comment]
Hi,

This is my bad, in some revisions forgot to add back the support for -1 for cacheDurationMinutes, I will submit a fix now, but changing line 169 in /src/filesystem-cache.ts https://github.com/GoogleChrome/rendertron/blob/0f64292ddfd46850f22dc33b360986e18d9b9628/src/filesystem-cache.ts#L169

to:
```javascript
if (content.expires.getTime() >= new Date().getTime() || parseInt(this.config.cacheConfig.cacheDurationMinutes) === -1) {
```

Should fix this

**Comment by art2limit** [comment]
well i change this line to:

    "cacheDurationMinutes": 72000,

and it's still not working :)

**Comment by dwsmart** [comment]
Strange, I've tested in Ubuntu & windows & seems to work for me, what os are you running on?

Does the user you are running rendertron as have the required permissions to create & write to the directory?

**Comment by art2limit** [comment]
yep, sorry, i add writing permissions and everything works ok :)
